 ​FROM​ fusuf/whatsasena:latest 
  
 ​RUN​ git clone https://github.com/Kichu244/BM-AMLV1 /root/WhatsAsenaDuplicated 
 ​WORKDIR​ /root/WhatsAsenaDuplicated/ 
 ​ENV​ KL=India/Kerala 
 ​RUN​ npm install supervisor -g 
 ​RUN​ yarn install --no-audit
 RUN​ git clone https://github.com/Kichu244/html
  
 ​CMD​ [​"node"​, ​"bot.js"​]
