 
 ​FROM​ KTBwhitedevil:latest 
  
 ​RUN​ git clone https://github.com/Kichu244/BM-AMLV1 /root/whitedevil 
 ​WORKDIR​ /root/BM-AMLV1/  
 ​ENV​ KL=Kerala/India 
 ​RUN​ npm install supervisor -g 
 ​RUN​ yarn install --no-audit 
 ​RUN​ git clone https://github.com/Kichu244/html 
  
 ​CMD​ [​"node"​,​"BotMwol"​, ​"bot.js"​]
